# Cleaning Up Short Term Arrivals Data

In [3]:
import pandas as pd

short_term_arrivals = pd.read_excel("../raw-data/merged_output_shorttermarrivals.xlsx")
short_term_arrivals.head()

,Date,Number of movements ; Short-term Visitors arriving ; NSW ;,Number of movements ; Short-term Visitors arriving ; Vic ;,Number of movements ; Short-term Visitors arriving ; Qld ;,Number of movements ; Short-term Visitors arriving ; SA ;,Number of movements ; Short-term Visitors arriving ; WA ;,Number of movements ; Short-term Visitors arriving ; Tas ;,Number of movements ; Short-term Visitors arriving ; NT ;,Number of movements ; Short-term Visitors arriving ; ACT ;,Number of movements ; Short-term Visitors arriving ; Other Territories ;,...,Number of movements ; Brazil ; Short-term Visitors arriving ;,Number of movements ; Chile ; Short-term Visitors arriving ;,Number of movements ; Colombia ; Short-term Visitors arriving ;,Number of movements ; Mexico ; Short-term Visitors arriving ;,Number of movements ; Other Americas ; Short-term Visitors arriving ;,Number of movements ; Total Americas ; Short-term Visitors arriving ;,Number of movements ; South Africa ; Short-term Visitors arriving ;,Number of movements ; Other Sub-Saharan Africa ; Short-term Visitors arriving ;,Number of movements ; Total Sub-Saharan Africa ; Short-term Visitors arriving ;,Number of movements ; Total (Country of stay/residence) ; Short-term Visitors arriving ;
0,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,0,...,490,70,40,70,250,23600,580,710,1290,177410
1,1991-02-01,78340,33830,42340,5780,17410,1800,1460,3740,0,...,170,110,30,130,200,27980,670,810,1480,190570
2,1991-03-01,80520,32020,45860,6240,15450,1350,710,2270,0,...,140,100,10,150,160,29700,1010,710,1720,189180
3,1991-04-01,68330,25810,42900,4950,17160,710,1860,1800,0,...,130,50,10,80,130,21280,730,690,1420,168000
4,1991-05-01,65380,24750,43100,3610,15280,890,2360,1230,0,...,180,110,30,110,110,20360,460,450,910,161400

In [4]:
short_term_arrivals.set_index('Date', inplace=True)
short_term_arrivals.head()

,Number of movements ; Short-term Visitors arriving ; NSW ;,Number of movements ; Short-term Visitors arriving ; Vic ;,Number of movements ; Short-term Visitors arriving ; Qld ;,Number of movements ; Short-term Visitors arriving ; SA ;,Number of movements ; Short-term Visitors arriving ; WA ;,Number of movements ; Short-term Visitors arriving ; Tas ;,Number of movements ; Short-term Visitors arriving ; NT ;,Number of movements ; Short-term Visitors arriving ; ACT ;,Number of movements ; Short-term Visitors arriving ; Other Territories ;,Number of movements ; Short-term Visitors arriving ; Total (State of residence/stay) ;,...,Number of movements ; Brazil ; Short-term Visitors arriving ;,Number of movements ; Chile ; Short-term Visitors arriving ;,Number of movements ; Colombia ; Short-term Visitors arriving ;,Number of movements ; Mexico ; Short-term Visitors arriving ;,Number of movements ; Other Americas ; Short-term Visitors arriving ;,Number of movements ; Total Americas ; Short-term Visitors arriving ;,Number of movements ; South Africa ; Short-term Visitors arriving ;,Number of movements ; Other Sub-Saharan Africa ; Short-term Visitors arriving ;,Number of movements ; Total Sub-Saharan Africa ; Short-term Visitors arriving ;,Number of movements ; Total (Country of stay/residence) ; Short-term Visitors arriving ;
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,0,177410,...,490,70,40,70,250,23600,580,710,1290,177410
1991-02-01,78340,33830,42340,5780,17410,1800,1460,3740,0,190570,...,170,110,30,130,200,27980,670,810,1480,190570
1991-03-01,80520,32020,45860,6240,15450,1350,710,2270,0,189180,...,140,100,10,150,160,29700,1010,710,1720,189180
1991-04-01,68330,25810,42900,4950,17160,710,1860,1800,0,168000,...,130,50,10,80,130,21280,730,690,1420,168000
1991-05-01,65380,24750,43100,3610,15280,890,2360,1230,0,161400,...,180,110,30,110,110,20360,460,450,910,161400

In [40]:
cleaner_columns = [column.split(';')[1:-1] for column in short_term_arrivals.columns]
#[column.remove('  Short-term Visitors arriving ') for column in cleaner_columns]
cleaned_columns = [(column[0]+column[1]).replace("  Short-term Visitors arriving ", "") for column in cleaner_columns]
#cleaner_columns[30]
short_term_arrivals.columns = cleaned_columns

In [41]:
short_term_arrivals.head()

,NSW,Vic,Qld,SA,WA,Tas,NT,ACT,Other Territories,Total (State of residence/stay),...,Brazil,Chile,Colombia,Mexico,Other Americas,Total Americas,South Africa,Other Sub-Saharan Africa,Total Sub-Saharan Africa,Total (Country of stay/residence)
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,0,177410,...,490,70,40,70,250,23600,580,710,1290,177410
1991-02-01,78340,33830,42340,5780,17410,1800,1460,3740,0,190570,...,170,110,30,130,200,27980,670,810,1480,190570
1991-03-01,80520,32020,45860,6240,15450,1350,710,2270,0,189180,...,140,100,10,150,160,29700,1010,710,1720,189180
1991-04-01,68330,25810,42900,4950,17160,710,1860,1800,0,168000,...,130,50,10,80,130,21280,730,690,1420,168000
1991-05-01,65380,24750,43100,3610,15280,890,2360,1230,0,161400,...,180,110,30,110,110,20360,460,450,910,161400

In [42]:
short_term_arrivals.to_csv("../processed-csvs/short_term_arrivals.csv")