# Combined Data

In [31]:
import pandas as pd
import numpy as np

# import datasets

PROCESSED_CSV_LOC = "../processed-csvs/"

economic_df = pd.read_csv(PROCESSED_CSV_LOC + "economic_data.csv")
visiting_visas_df = pd.read_csv(PROCESSED_CSV_LOC + "visiting_visas_by_state.csv")
short_term_arrivals_df = pd.read_csv(PROCESSED_CSV_LOC + "short_term_arrivals.csv")
bitre_df = pd.read_csv("../raw-csvs/bitre/seat_utilisation.csv")
bitre_df.set_index("MONTH", inplace=True)

In [11]:
# Inspect the data
economic_df.head()

,Unnamed: 0,Country Code,year,Country Name,gdp_per_capita,gdp,inflation,unemployment
0,0,ABW,1960,Aruba,NaN,NaN,NaN,NaN
1,1,ABW,1961,Aruba,NaN,NaN,NaN,NaN
2,2,ABW,1962,Aruba,NaN,NaN,NaN,NaN
3,3,ABW,1963,Aruba,NaN,NaN,NaN,NaN
4,4,ABW,1964,Aruba,NaN,NaN,NaN,NaN

In [12]:
visiting_visas_df.head()

  year_month state  arrivals
0    1991-01   NSW     75630
1    1991-01   QLD     42710
2    1991-01   TAS      1410
3    1991-01   ACT      1990
4    1991-01    NT      1220

In [13]:
short_term_arrivals_df.head()

,Date,NSW,Vic,Qld,SA,WA,Tas,NT,ACT,Other Territories,...,Brazil,Chile,Colombia,Mexico,Other Americas,Total Americas,South Africa,Other Sub-Saharan Africa,Total Sub-Saharan Africa,Total (Country of stay/residence)
0,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,0,...,490,70,40,70,250,23600,580,710,1290,177410
1,1991-02-01,78340,33830,42340,5780,17410,1800,1460,3740,0,...,170,110,30,130,200,27980,670,810,1480,190570
2,1991-03-01,80520,32020,45860,6240,15450,1350,710,2270,0,...,140,100,10,150,160,29700,1010,710,1720,189180
3,1991-04-01,68330,25810,42900,4950,17160,710,1860,1800,0,...,130,50,10,80,130,21280,730,690,1420,168000
4,1991-05-01,65380,24750,43100,3610,15280,890,2360,1230,0,...,180,110,30,110,110,20360,460,450,910,161400

In [14]:
# get rid of the first column in economic_df
economic_df = economic_df.iloc[:,1:]

In [15]:
economic_df.head()

,Country Code,year,Country Name,gdp_per_capita,gdp,inflation,unemployment
0,ABW,1960,Aruba,NaN,NaN,NaN,NaN
1,ABW,1961,Aruba,NaN,NaN,NaN,NaN
2,ABW,1962,Aruba,NaN,NaN,NaN,NaN
3,ABW,1963,Aruba,NaN,NaN,NaN,NaN
4,ABW,1964,Aruba,NaN,NaN,NaN,NaN

## Create First Dataset on Australia Arrival Numbers

In [32]:
# Sum visiting visas state numbers to get total numbers each month
visiting_visas_df = visiting_visas_df.groupby("year_month", as_index=False)["arrivals"].sum()

# convert year_month to date column
visiting_visas_df["Date"] = pd.to_datetime(visiting_visas_df["year_month"], format="%Y-%m")
visiting_visas_df.drop(columns='year_month', inplace=True)

# Convert short term arrivals to date time as well
short_term_arrivals_df["Date"] = pd.to_datetime(short_term_arrivals_df["Date"], format='%Y-%m-%d')
short_term_arrivals_df.head()

,Date,NSW,Vic,Qld,SA,WA,Tas,NT,ACT,Other Territories,...,Brazil,Chile,Colombia,Mexico,Other Americas,Total Americas,South Africa,Other Sub-Saharan Africa,Total Sub-Saharan Africa,Total (Country of stay/residence)
0,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,0,...,490,70,40,70,250,23600,580,710,1290,177410
1,1991-02-01,78340,33830,42340,5780,17410,1800,1460,3740,0,...,170,110,30,130,200,27980,670,810,1480,190570
2,1991-03-01,80520,32020,45860,6240,15450,1350,710,2270,0,...,140,100,10,150,160,29700,1010,710,1720,189180
3,1991-04-01,68330,25810,42900,4950,17160,710,1860,1800,0,...,130,50,10,80,130,21280,730,690,1420,168000
4,1991-05-01,65380,24750,43100,3610,15280,890,2360,1230,0,...,180,110,30,110,110,20360,460,450,910,161400

In [33]:
# Combine with short term arrivals data

combined_df = visiting_visas_df.merge(short_term_arrivals_df, on="Date", how="left")
combined_df.head()

,arrivals,Date,NSW,Vic,Qld,SA,WA,Tas,NT,ACT,...,Brazil,Chile,Colombia,Mexico,Other Americas,Total Americas,South Africa,Other Sub-Saharan Africa,Total Sub-Saharan Africa,Total (Country of stay/residence)
0,170520,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,...,490,70,40,70,250,23600,580,710,1290,177410
1,184700,1991-02-01,78340,33830,42340,5780,17410,1800,1460,3740,...,170,110,30,130,200,27980,670,810,1480,190570
2,184420,1991-03-01,80520,32020,45860,6240,15450,1350,710,2270,...,140,100,10,150,160,29700,1010,710,1720,189180
3,163520,1991-04-01,68330,25810,42900,4950,17160,710,1860,1800,...,130,50,10,80,130,21280,730,690,1420,168000
4,156600,1991-05-01,65380,24750,43100,3610,15280,890,2360,1230,...,180,110,30,110,110,20360,460,450,910,161400

In [40]:
bitre_df.head()

,AIRLINE,COUNTRY,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,FIN_Y,CAL_Y,Date
MONTH,,,,,,,,,,,
1991-01-01,Aerolineas Argentinas,Argentina,10,2378,3000,10,1587,3000,1991,1991,1991-01-01
1991-01-01,Air Caledonie,New Caledonia,22,2645,2860,21,1761,2730,1991,1991,1991-01-01
1991-01-01,Air China,China,4,1028,1060,4,741,1060,1991,1991,1991-01-01
1991-01-01,Air India,India,9,1440,3393,9,2150,3393,1991,1991,1991-01-01
1991-01-01,Nauru Airlines,Nauru,5,334,493,6,360,592,1991,1991,1991-01-01

In [39]:
combined_df = combined_df.merge(bitre_df, on="Date", how="left")
combined_df.head()

,arrivals,Date,NSW,Vic,Qld,SA,WA,Tas,NT,ACT,...,AIRLINE,COUNTRY,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,FIN_Y,CAL_Y
0,170520,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,...,Aerolineas Argentinas,Argentina,10,2378,3000,10,1587,3000,1991.0,1991.0
1,170520,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,...,Air Caledonie,New Caledonia,22,2645,2860,21,1761,2730,1991.0,1991.0
2,170520,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,...,Air China,China,4,1028,1060,4,741,1060,1991.0,1991.0
3,170520,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,...,Air India,India,9,1440,3393,9,2150,3393,1991.0,1991.0
4,170520,1991-01-01,75630,28840,42710,4930,13790,1410,1220,1990,...,Nauru Airlines,Nauru,5,334,493,6,360,592,1991.0,1991.0

In [58]:
# Remove state columns from dataset
combined_df.columns = [column.strip() for column in combined_df.columns]
combined_df.drop(columns=[
    'NSW','Vic','Qld','SA','WA','Tas',
    'NT','ACT','Other Territories', 'Total (State of residence/stay)'
],inplace=True)

In [59]:
combined_df.columns

Index(['arrivals', 'Date', 'Under 1 week', '1 and under 2 weeks',
       '2 weeks and under 1 month', '1 and under 2 months',
       '2 and under 3 months', '3 and under 6 months', '6 and under 12 months',
       'Total (Duration of stay in days)', 'Convention/conference', 'Business',
       'Visiting friends/relatives', 'Holiday', 'Employment', 'Education',
       'Other & not stated', 'Total (Reason for Journey)', 'New Zealand',
       'New Caledonia', 'Papua New Guinea', 'Vanuatu', 'Fiji',
       'Other Oceania and Antarctica', 'Total Oceania and Antarctica',
       'UK, CIs & IOM', 'Ireland', 'Austria', 'Belgium', 'France', 'Germany',
       'Netherlands', 'Switzerland', 'Denmark', 'Finland', 'Norway', 'Sweden',
       'Other North-West Europe', 'Total North-West Europe', 'Italy', 'Spain',
       'Poland', 'Russian Federation', 'Other Southern and Eastern Europe',
       'Total Southern and Eastern Europe', 'Iran', 'Israel', 'Saudi Arabia',
       'United Arab Emirates', 'Other North Africa and the Middle East',
       'Total North Africa and the Middle East', 'Cambodia', 'Thailand',
       'Vietnam', 'Indonesia', 'Malaysia', 'Philippines', 'Singapore',
       'Other South-East Asia', 'Total South-East Asia', 'China', 'Hong Kong',
       'Taiwan', 'Japan', 'Korea, South', 'Other North-East Asia',
       'Total North-East Asia', 'Bangladesh', 'India', 'Nepal', 'Pakistan',
       'Sri Lanka', 'Other Southern and Central Asia',
       'Total Southern and Central Asia', 'Canada', 'United States of America',
       'Argentina', 'Brazil', 'Chile', 'Colombia', 'Mexico', 'Other Americas',
       'Total Americas', 'South Africa', 'Other Sub-Saharan Africa',
       'Total Sub-Saharan Africa', 'Total (Country of stay/residence)',
       'AIRLINE', 'COUNTRY', 'FLTS IN', 'PAX IN', 'SEATS IN', 'FLTS OUT',
       'PAX OUT', 'SEATS OUT', 'FIN_Y', 'CAL_Y'],
      dtype='object')

In [60]:
# Melt to long format
combined_long_df = pd.melt(combined_df, id_vars=["Date"], value_vars=['New Zealand',
       'New Caledonia', 'Papua New Guinea', 'Vanuatu', 'Fiji',
       'Other Oceania and Antarctica', 'Total Oceania and Antarctica',
       'UK, CIs & IOM', 'Ireland', 'Austria', 'Belgium', 'France', 'Germany',
       'Netherlands', 'Switzerland', 'Denmark', 'Finland', 'Norway', 'Sweden',
       'Other North-West Europe', 'Total North-West Europe', 'Italy', 'Spain',
       'Poland', 'Russian Federation', 'Other Southern and Eastern Europe',
       'Total Southern and Eastern Europe', 'Iran', 'Israel', 'Saudi Arabia',
       'United Arab Emirates', 'Other North Africa and the Middle East',
       'Total North Africa and the Middle East', 'Cambodia', 'Thailand',
       'Vietnam', 'Indonesia', 'Malaysia', 'Philippines', 'Singapore',
       'Other South-East Asia', 'Total South-East Asia', 'China', 'Hong Kong',
       'Taiwan', 'Japan', 'Korea, South', 'Other North-East Asia',
       'Total North-East Asia', 'Bangladesh', 'India', 'Nepal', 'Pakistan',
       'Sri Lanka', 'Other Southern and Central Asia',
       'Total Southern and Central Asia', 'Canada', 'United States of America',
       'Argentina', 'Brazil', 'Chile', 'Colombia', 'Mexico', 'Other Americas',
       'Total Americas', 'South Africa', 'Other Sub-Saharan Africa',
       'Total Sub-Saharan Africa'])
combined_long_df.head()

        Date     variable  value
0 1991-01-01  New Zealand  26140
1 1991-01-01  New Zealand  26140
2 1991-01-01  New Zealand  26140
3 1991-01-01  New Zealand  26140
4 1991-01-01  New Zealand  26140

In [66]:
combined_long_df.rename(columns={'variable':'Country/Continent'}, inplace=True)
combined_long_df.head()

        Date Country/Continent  value
0 1991-01-01       New Zealand  26140
1 1991-01-01       New Zealand  26140
2 1991-01-01       New Zealand  26140
3 1991-01-01       New Zealand  26140
4 1991-01-01       New Zealand  26140

In [69]:
# Combine with economic data
economic_df.rename(columns={'Country Name':'Country/Continent','year':'Year'}, inplace=True)
combined_long_df["Year"] = combined_long_df["Date"].dt.year
merged_df = combined_long_df.merge(economic_df, on=["Year","Country/Continent"], how="inner")
merged_df.head()

,Date,Country/Continent,value,Year,Unnamed: 0,Country Code,gdp_per_capita,gdp,inflation,unemployment
0,1991-01-01,New Zealand,26140,1991,11666,NZL,12230.073455,4.274533e+10,2.602393,10.614
1,1991-01-01,New Zealand,26140,1991,11666,NZL,12230.073455,4.274533e+10,2.602393,10.614
2,1991-01-01,New Zealand,26140,1991,11666,NZL,12230.073455,4.274533e+10,2.602393,10.614
3,1991-01-01,New Zealand,26140,1991,11666,NZL,12230.073455,4.274533e+10,2.602393,10.614
4,1991-01-01,New Zealand,26140,1991,11666,NZL,12230.073455,4.274533e+10,2.602393,10.614

In [71]:
merged_df.drop(columns='Unnamed: 0',inplace=True)

In [79]:
merged_df.drop_duplicates(inplace=True)

In [82]:
merged_df = merged_df.merge(combined_df.loc[:,['Date','Under 1 week', '1 and under 2 weeks',
       '2 weeks and under 1 month', '1 and under 2 months',
       '2 and under 3 months', '3 and under 6 months', '6 and under 12 months',
       'Total (Duration of stay in days)', 'Convention/conference', 'Business',
       'Visiting friends/relatives', 'Holiday', 'Employment', 'Education',
       'Other & not stated', 'Total (Reason for Journey)']], on='Date', how='left').drop_duplicates()

In [83]:
merged_df.shape

(17544, 25)

In [85]:
merged_df.drop(columns=['Total (Duration of stay in days)','Total (Reason for Journey)'],inplace=True)
merged_df.rename(columns={'value':'Arrivals'}, inplace=True)
merged_df.columns

Index(['Date', 'Country/Continent', 'Arrivals', 'Year', 'Country Code',
       'gdp_per_capita', 'gdp', 'inflation', 'unemployment', 'Under 1 week',
       '1 and under 2 weeks', '2 weeks and under 1 month',
       '1 and under 2 months', '2 and under 3 months', '3 and under 6 months',
       '6 and under 12 months', 'Convention/conference', 'Business',
       'Visiting friends/relatives', 'Holiday', 'Employment', 'Education',
       'Other & not stated'],
      dtype='object')

In [86]:
cols=  ['Under 1 week', '1 and under 2 weeks', '2 weeks and under 1 month', '1 and under 2 months', '2 and under 3 months', '3 and under 6 months', '6 and under 12 months']

# Compute row sums
row_totals = merged_df[cols].sum(axis=1)

# Divide each column by its row total
merged_df[cols] = merged_df[cols].div(row_totals, axis=0)
merged_df.head()

,Date,Country/Continent,Arrivals,Year,Country Code,gdp_per_capita,gdp,inflation,unemployment,Under 1 week,...,2 and under 3 months,3 and under 6 months,6 and under 12 months,Convention/conference,Business,Visiting friends/relatives,Holiday,Employment,Education,Other & not stated
0,1991-01-01,New Zealand,26140,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.250648,...,0.045203,0.053996,0.095705,1730,13650,28790,108880,2610,9860,11900
61,1991-02-01,New Zealand,26630,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.228711,...,0.041713,0.045858,0.088200,3670,18300,35250,109100,1670,10890,11690
121,1991-03-01,New Zealand,37290,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.224430,...,0.035308,0.037898,0.046250,1990,18610,40060,111670,1650,3690,11510
179,1991-04-01,New Zealand,32000,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.285060,...,0.030060,0.036488,0.054048,2140,20880,33930,96700,2650,4190,7520
238,1991-05-01,New Zealand,44500,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.330855,...,0.025774,0.033333,0.038848,2870,17810,30210,96510,2550,2830,8630

In [87]:
cols= ['Convention/conference', 'Business',
       'Visiting friends/relatives', 'Holiday', 'Employment', 'Education',
       'Other & not stated']

# Compute row sums
row_totals = merged_df[cols].sum(axis=1)

# Divide each column by its row total
merged_df[cols] = merged_df[cols].div(row_totals, axis=0)
merged_df.head()

,Date,Country/Continent,Arrivals,Year,Country Code,gdp_per_capita,gdp,inflation,unemployment,Under 1 week,...,2 and under 3 months,3 and under 6 months,6 and under 12 months,Convention/conference,Business,Visiting friends/relatives,Holiday,Employment,Education,Other & not stated
0,1991-01-01,New Zealand,26140,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.250648,...,0.045203,0.053996,0.095705,0.009751,0.076936,0.162270,0.613685,0.014711,0.055574,0.067072
61,1991-02-01,New Zealand,26630,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.228711,...,0.041713,0.045858,0.088200,0.019258,0.096028,0.184971,0.572493,0.008763,0.057144,0.061342
121,1991-03-01,New Zealand,37290,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.224430,...,0.035308,0.037898,0.046250,0.010519,0.098372,0.211756,0.590284,0.008722,0.019505,0.060842
179,1991-04-01,New Zealand,32000,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.285060,...,0.030060,0.036488,0.054048,0.012737,0.124278,0.201952,0.575561,0.015773,0.024939,0.044759
238,1991-05-01,New Zealand,44500,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.330855,...,0.025774,0.033333,0.038848,0.017781,0.110340,0.187163,0.597918,0.015798,0.017533,0.053466

In [154]:
new_bitre_df = bitre_df.drop(columns=['AIRLINE','FIN_Y','CAL_Y'])
new_bitre_df.replace('..', np.nan, inplace=True)
new_bitre_df.replace('(d)', np.nan, inplace=True)
new_bitre_df.replace('(e)', np.nan, inplace=True)
new_bitre_df.replace('-', np.nan, inplace=True)
new_bitre_df.replace('(f)', np.nan, inplace=True)
new_bitre_df.replace('(a)', np.nan, inplace=True)
new_bitre_df.replace('(b)', np.nan, inplace=True)
new_bitre_df.replace('(h)', np.nan, inplace=True)
new_bitre_df.replace('(c)', np.nan, inplace=True)
new_bitre_df.replace('(l)', np.nan, inplace=True)
new_bitre_df.replace('(g)', np.nan, inplace=True)
new_bitre_df.replace('(v)', np.nan, inplace=True)
new_bitre_df.replace('(k)', np.nan, inplace=True)
new_bitre_df.replace('(z)', np.nan, inplace=True)
new_bitre_df['PAX IN'] = new_bitre_df['PAX IN'].str.replace(" ", "")
new_bitre_df['SEATS IN'] = new_bitre_df['SEATS IN'].str.replace(" ", "")
new_bitre_df['PAX OUT'] = new_bitre_df['PAX OUT'].str.replace(" ", "")
new_bitre_df['SEATS OUT'] = new_bitre_df['SEATS OUT'].str.replace(" ", "")

#new_bitre_df["COUNTRY"] = new_bitre_df["COUNTRY"].astype('category')
new_bitre_df["FLTS IN"] = new_bitre_df["FLTS IN"].astype('float')
new_bitre_df["PAX IN"] = new_bitre_df["PAX IN"].astype('float')
new_bitre_df["SEATS IN"] = new_bitre_df["SEATS IN"].astype('float')
new_bitre_df["FLTS OUT"] = new_bitre_df["FLTS OUT"].astype('float')
new_bitre_df["PAX OUT"] = new_bitre_df["PAX OUT"].astype('float')
new_bitre_df["SEATS OUT"] = new_bitre_df["SEATS OUT"].astype('float')

new_bitre_df.dtypes

COUNTRY              object
FLTS IN             float64
PAX IN              float64
SEATS IN            float64
FLTS OUT            float64
PAX OUT             float64
SEATS OUT           float64
Date         datetime64[ns]
dtype: object

In [155]:
new_bitre_df.head()

,COUNTRY,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,Date
MONTH,,,,,,,,
1991-01-01,Argentina,10.0,2378.0,3000.0,10.0,1587.0,3000.0,1991-01-01
1991-01-01,New Caledonia,22.0,2645.0,2860.0,21.0,1761.0,2730.0,1991-01-01
1991-01-01,China,4.0,1028.0,1060.0,4.0,741.0,1060.0,1991-01-01
1991-01-01,India,9.0,1440.0,3393.0,9.0,2150.0,3393.0,1991-01-01
1991-01-01,Nauru,5.0,334.0,493.0,6.0,360.0,592.0,1991-01-01

In [159]:
totals = new_bitre_df.groupby(by=["COUNTRY","Date"],as_index=False).sum()
totals.rename(columns={'COUNTRY':'Country/Continent'}, inplace=True)
totals

,Country/Continent,Date,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT
0,American Samoa,1991-01-01,2.0,72.0,370.0,2.0,29.0,370.0
1,American Samoa,1991-02-01,4.0,289.0,740.0,4.0,279.0,740.0
2,American Samoa,1991-03-01,5.0,495.0,925.0,5.0,720.0,925.0
3,American Samoa,1991-04-01,2.0,156.0,535.0,2.0,184.0,535.0
4,Argentina,1991-01-01,10.0,2687.0,3500.0,10.0,1743.0,3500.0
...,...,...,...,...,...,...,...,...
14486,Zimbabwe,2000-02-01,0.0,66.0,192.0,0.0,25.0,253.0
14487,Zimbabwe,2000-03-01,0.0,64.0,200.0,0.0,50.0,276.0
14488,Zimbabwe,2000-04-01,0.0,23.0,165.0,0.0,31.0,173.0
14489,Zimbabwe,2000-05-01,0.0,16.0,266.0,0.0,21.0,204.0
14490,Zimbabwe,2000-06-01,0.0,31.0,238.0,0.0,31.0,297.0

In [170]:
even_more_merged_df = merged_df.merge(totals, on=["Date","Country/Continent"], how="left")

In [161]:
rba_exchange_rates = pd.read_csv("../processed-csvs/rba_interest_rates.csv")
rba_exchange_rates.head()

,Unnamed: 0,Date,JPY,USD,EUR,KRW,NZD,CNY,GBP,TWD,...,THB,VND,AED,PGK,CAD,ZAR,SAR,CHF,SEK,PHP
0,0,1969-07-31,400.74,1.1138,NaN,NaN,0.998,NaN,0.4657,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1969-08-31,398.14,1.1091,NaN,NaN,0.998,NaN,0.4657,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1969-09-30,396.81,1.1094,NaN,NaN,0.998,NaN,0.4657,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1969-10-31,399.02,1.1158,NaN,NaN,0.998,NaN,0.4657,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1969-11-30,399.08,1.1161,NaN,NaN,0.998,NaN,0.4657,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [164]:
rba_exchange_rates.set_index("Date", inplace=True)

In [166]:
rba_exchange_rates.drop(columns="Unnamed: 0",inplace=True)
rba_exchange_rates

,JPY,USD,EUR,KRW,NZD,CNY,GBP,TWD,SGD,IDR,...,THB,VND,AED,PGK,CAD,ZAR,SAR,CHF,SEK,PHP
Date,,,,,,,,,,,,,,,,,,,,,
1969-07-31,400.74,1.1138,NaN,NaN,0.9980,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-08-31,398.14,1.1091,NaN,NaN,0.9980,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-09-30,396.81,1.1094,NaN,NaN,0.9980,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-10-31,399.02,1.1158,NaN,NaN,0.9980,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-11-30,399.08,1.1161,NaN,NaN,0.9980,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-31,93.62,0.6280,0.5796,923.63,1.1004,4.5548,0.4847,20.86,0.8421,10400.0,...,21.31,16049.0,2.3063,NaN,0.8990,NaN,NaN,0.5521,NaN,35.98
2025-04-30,91.43,0.6416,0.5637,911.63,1.0794,4.6613,0.4788,20.52,0.8375,10686.0,...,21.38,16680.0,2.3563,NaN,0.8871,NaN,NaN,0.5283,NaN,35.83
2025-05-30,92.57,0.6436,0.5670,887.78,1.0764,4.6259,0.4775,19.26,0.8295,10484.0,...,21.03,16732.0,2.3636,NaN,0.8890,NaN,NaN,0.5296,NaN,35.80
2025-06-30,94.26,0.6550,0.5586,883.89,1.0768,4.6921,0.4771,19.07,0.8341,10629.0,...,21.29,17087.0,2.4055,NaN,0.8947,NaN,NaN,0.5228,NaN,36.88
2025-07-31,96.25,0.6469,0.5656,899.32,1.0911,4.6532,0.4877,19.36,0.8376,10651.0,...,21.17,16955.0,2.3757,NaN,0.8940,NaN,NaN,0.5257,NaN,37.78

In [167]:
rba_exchange_rates[rba_exchange_rates.index > "1991-01-01"]

,JPY,USD,EUR,KRW,NZD,CNY,GBP,TWD,SGD,IDR,...,THB,VND,AED,PGK,CAD,ZAR,SAR,CHF,SEK,PHP
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-31,102.94,0.7849,NaN,564.34,1.3080,4.0988,0.4002,21.28,1.3588,1501.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-02-28,103.65,0.7851,NaN,568.73,1.3105,4.0999,0.4087,21.32,1.3555,1507.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-03-31,108.40,0.7752,NaN,562.41,1.3202,4.0482,0.4467,21.21,1.3926,1498.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-04-30,107.35,0.7817,NaN,566.81,1.3326,4.1332,0.4613,21.40,1.3842,1516.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-05-31,104.91,0.7609,NaN,550.13,1.3036,4.0599,0.4445,20.69,1.3428,1482.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-31,93.62,0.6280,0.5796,923.63,1.1004,4.5548,0.4847,20.86,0.8421,10400.0,...,21.31,16049.0,2.3063,NaN,0.8990,NaN,NaN,0.5521,NaN,35.98
2025-04-30,91.43,0.6416,0.5637,911.63,1.0794,4.6613,0.4788,20.52,0.8375,10686.0,...,21.38,16680.0,2.3563,NaN,0.8871,NaN,NaN,0.5283,NaN,35.83
2025-05-30,92.57,0.6436,0.5670,887.78,1.0764,4.6259,0.4775,19.26,0.8295,10484.0,...,21.03,16732.0,2.3636,NaN,0.8890,NaN,NaN,0.5296,NaN,35.80
2025-06-30,94.26,0.6550,0.5586,883.89,1.0768,4.6921,0.4771,19.07,0.8341,10629.0,...,21.29,17087.0,2.4055,NaN,0.8947,NaN,NaN,0.5228,NaN,36.88
2025-07-31,96.25,0.6469,0.5656,899.32,1.0911,4.6532,0.4877,19.36,0.8376,10651.0,...,21.17,16955.0,2.3757,NaN,0.8940,NaN,NaN,0.5257,NaN,37.78

In [183]:
rba_exchange_rates.rename(columns={"JPY": "Japan",
    "USD": "United States of America",
    "EUR": "Eurozone countries",
    "KRW": "South Korea",
    "NZD": "New Zealand",
    "CNY": "China",
    "GBP": "United Kingdom",
    "TWD": "Taiwan",
    "SGD": "Singapore",
    "IDR": "Indonesia",
    "HKD": "Hong Kong",
    "MYR": "Malaysia",
    "SDR": "International Monetary Fund (IMF Special Drawing Rights)",
    "INR": "India",
    "THB": "Thailand",
    "VND": "Vietnam",
    "AED": "United Arab Emirates",
    "PGK": "Papua New Guinea",
    "CAD": "Canada",
    "ZAR": "South Africa",
    "SAR": "Saudi Arabia",
    "CHF": "Switzerland",
    "SEK": "Sweden",
    "PHP": "Philippines"}, inplace=True)
rba_exchange_rates.head()

,Japan,United States of America,Eurozone countries,South Korea,New Zealand,China,United Kingdom,Taiwan,Singapore,Indonesia,...,Thailand,Vietnam,United Arab Emirates,Papua New Guinea,Canada,South Africa,Saudi Arabia,Switzerland,Sweden,Philippines
Date,,,,,,,,,,,,,,,,,,,,,
1969-07-31,400.74,1.1138,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-08-31,398.14,1.1091,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-09-30,396.81,1.1094,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-10-31,399.02,1.1158,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969-11-30,399.08,1.1161,NaN,NaN,0.998,NaN,0.4657,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [185]:
rba_exchange_rates["Date"] = rba_exchange_rates.index
rba_exchange_rates_melted = pd.melt(rba_exchange_rates, id_vars=["Date"], value_vars=["Japan",
    "United States of America",
    "Eurozone countries",
    "South Korea",
    "New Zealand",
    "China",
    "United Kingdom",
    "Taiwan",
    "Singapore",
    "Indonesia",
    "Hong Kong",
    "Malaysia",
    "International Monetary Fund (IMF Special Drawing Rights)",
    "India",
    "Thailand",
    "Vietnam",
    "United Arab Emirates",
    "Papua New Guinea",
    "Canada",
    "South Africa",
    "Saudi Arabia",
    "Switzerland",
    "Sweden",
    "Philippines",
    "Index"])
rba_exchange_rates_melted.head()

         Date variable   value
0  1969-07-31    Japan  400.74
1  1969-08-31    Japan  398.14
2  1969-09-30    Japan  396.81
3  1969-10-31    Japan  399.02
4  1969-11-30    Japan  399.08

In [189]:
rba_exchange_rates_melted.shape
rba_exchange_rates_melted.rename(columns={"variable":"Country/Continent"}, inplace=True)

In [193]:
df_twi = rba_exchange_rates_melted[rba_exchange_rates_melted["Country/Continent"] == "Index"].copy()
df_twi = df_twi.rename(columns={"value": "TWI"})  # rename for clarity
df_twi = df_twi[["Date", "TWI"]] # keep only needed columns
df_twi

             Date   TWI
16152  1969-07-31   NaN
16153  1969-08-31   NaN
16154  1969-09-30   NaN
16155  1969-10-31   NaN
16156  1969-11-30   NaN
...           ...   ...
16820  2025-03-31  59.6
16821  2025-04-30  59.9
16822  2025-05-30  59.6
16823  2025-06-30  60.1
16824  2025-07-31  60.3

[673 rows x 2 columns]

In [208]:
df_non_index = rba_exchange_rates_melted[rba_exchange_rates_melted["Country/Continent"] != "Index"].copy()
df_non_index["Date"] = pd.to_datetime(df_non_index["Date"], format='%Y-%m-%d')

In [251]:
even_more_merged_df["Year"] = even_more_merged_df["Date"].dt.year
even_more_merged_df["Month"] = even_more_merged_df["Date"].dt.month

In [252]:
df_non_index["Year"] = df_non_index["Date"].dt.year
df_non_index["Month"] = df_non_index["Date"].dt.month

In [253]:
even_more_merged_df.head()

,Date,Country/Continent,Arrivals,Year,Country Code,gdp_per_capita,gdp,inflation,unemployment,Under 1 week,...,Employment,Education,Other & not stated,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,Month
0,1991-01-01,New Zealand,26140,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.250648,...,0.014711,0.055574,0.067072,480.0,79182.0,115531.0,480.0,69951.0,114745.0,1
1,1991-02-01,New Zealand,26630,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.228711,...,0.008763,0.057144,0.061342,411.0,59457.0,99283.0,409.0,59593.0,98687.0,2
2,1991-03-01,New Zealand,37290,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.224430,...,0.008722,0.019505,0.060842,472.0,69918.0,112703.0,467.0,66590.0,111108.0,3
3,1991-04-01,New Zealand,32000,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.285060,...,0.015773,0.024939,0.044759,422.0,56856.0,98872.0,429.0,55901.0,100985.0,4
4,1991-05-01,New Zealand,44500,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.330855,...,0.015798,0.017533,0.053466,447.0,62983.0,104890.0,445.0,58146.0,104503.0,5

In [254]:
with_exchange_rates = even_more_merged_df.merge(df_non_index, on=["Year","Month", "Country/Continent"], how="left")
with_exchange_rates

,Date_x,Country/Continent,Arrivals,Year,Country Code,gdp_per_capita,gdp,inflation,unemployment,Under 1 week,...,Other & not stated,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,Month,Date_y,value
0,1991-01-01,New Zealand,26140,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.250648,...,0.067072,480.0,79182.0,115531.0,480.0,69951.0,114745.0,1,1991-01-31,1.3080
1,1991-02-01,New Zealand,26630,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.228711,...,0.061342,411.0,59457.0,99283.0,409.0,59593.0,98687.0,2,1991-02-28,1.3105
2,1991-03-01,New Zealand,37290,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.224430,...,0.060842,472.0,69918.0,112703.0,467.0,66590.0,111108.0,3,1991-03-31,1.3202
3,1991-04-01,New Zealand,32000,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.285060,...,0.044759,422.0,56856.0,98872.0,429.0,55901.0,100985.0,4,1991-04-30,1.3326
4,1991-05-01,New Zealand,44500,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.330855,...,0.053466,447.0,62983.0,104890.0,445.0,58146.0,104503.0,5,1991-05-31,1.3036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,2024-08-01,South Africa,3140,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.266743,...,0.039951,40.0,9226.0,9651.0,40.0,8944.0,9652.0,8,2024-08-30,NaN
17540,2024-09-01,South Africa,3460,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.248363,...,0.040446,39.0,9497.0,9661.0,39.0,8819.0,9666.0,9,2024-09-30,NaN
17541,2024-10-01,South Africa,4120,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.280126,...,0.042057,37.0,13205.0,14229.0,37.0,10445.0,14686.0,10,2024-10-31,NaN
17542,2024-11-01,South Africa,5150,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.268753,...,0.038958,35.0,12006.0,13720.0,35.0,11126.0,14181.0,11,2024-11-29,NaN
17543,2024-12-01,South Africa,9350,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.165591,...,0.022893,43.0,14636.0,16380.0,42.0,14688.0,16647.0,12,2024-12-31,NaN

In [256]:
with_exchange_rates.drop(columns=["Date_y"], inplace=True)
with_exchange_rates.rename(columns={"Date_x":"Date"}, inplace=True)

In [258]:
df_twi["Date"] = pd.to_datetime(df_twi["Date"], format='%Y-%m-%d')
df_twi["Year"] = df_twi["Date"].dt.year
df_twi["Month"] = df_twi["Date"].dt.month

In [260]:
with_even_more_exchange_rates = with_exchange_rates.merge(df_twi, on=["Year","Month"], how="left")
with_even_more_exchange_rates

,Date_x,Country/Continent,Arrivals,Year,Country Code,gdp_per_capita,gdp,inflation,unemployment,Under 1 week,...,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,Month,value,Date_y,TWI
0,1991-01-01,New Zealand,26140,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.250648,...,480.0,79182.0,115531.0,480.0,69951.0,114745.0,1,1.3080,1991-01-31,57.5
1,1991-02-01,New Zealand,26630,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.228711,...,411.0,59457.0,99283.0,409.0,59593.0,98687.0,2,1.3105,1991-02-28,57.9
2,1991-03-01,New Zealand,37290,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.224430,...,472.0,69918.0,112703.0,467.0,66590.0,111108.0,3,1.3202,1991-03-31,59.7
3,1991-04-01,New Zealand,32000,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.285060,...,422.0,56856.0,98872.0,429.0,55901.0,100985.0,4,1.3326,1991-04-30,60.2
4,1991-05-01,New Zealand,44500,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.330855,...,447.0,62983.0,104890.0,445.0,58146.0,104503.0,5,1.3036,1991-05-31,58.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,2024-08-01,South Africa,3140,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.266743,...,40.0,9226.0,9651.0,40.0,8944.0,9652.0,8,NaN,2024-08-30,62.6
17540,2024-09-01,South Africa,3460,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.248363,...,39.0,9497.0,9661.0,39.0,8819.0,9666.0,9,NaN,2024-09-30,62.8
17541,2024-10-01,South Africa,4120,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.280126,...,37.0,13205.0,14229.0,37.0,10445.0,14686.0,10,NaN,2024-10-31,61.5
17542,2024-11-01,South Africa,5150,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.268753,...,35.0,12006.0,13720.0,35.0,11126.0,14181.0,11,NaN,2024-11-29,61.5
17543,2024-12-01,South Africa,9350,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.165591,...,43.0,14636.0,16380.0,42.0,14688.0,16647.0,12,NaN,2024-12-31,59.7

In [261]:
with_even_more_exchange_rates["value"] = with_even_more_exchange_rates["value"].fillna(with_even_more_exchange_rates["TWI"])
with_even_more_exchange_rates

,Date_x,Country/Continent,Arrivals,Year,Country Code,gdp_per_capita,gdp,inflation,unemployment,Under 1 week,...,FLTS IN,PAX IN,SEATS IN,FLTS OUT,PAX OUT,SEATS OUT,Month,value,Date_y,TWI
0,1991-01-01,New Zealand,26140,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.250648,...,480.0,79182.0,115531.0,480.0,69951.0,114745.0,1,1.3080,1991-01-31,57.5
1,1991-02-01,New Zealand,26630,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.228711,...,411.0,59457.0,99283.0,409.0,59593.0,98687.0,2,1.3105,1991-02-28,57.9
2,1991-03-01,New Zealand,37290,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.224430,...,472.0,69918.0,112703.0,467.0,66590.0,111108.0,3,1.3202,1991-03-31,59.7
3,1991-04-01,New Zealand,32000,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.285060,...,422.0,56856.0,98872.0,429.0,55901.0,100985.0,4,1.3326,1991-04-30,60.2
4,1991-05-01,New Zealand,44500,1991,NZL,12230.073455,4.274533e+10,2.602393,10.614,0.330855,...,447.0,62983.0,104890.0,445.0,58146.0,104503.0,5,1.3036,1991-05-31,58.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,2024-08-01,South Africa,3140,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.266743,...,40.0,9226.0,9651.0,40.0,8944.0,9652.0,8,62.6000,2024-08-30,62.6
17540,2024-09-01,South Africa,3460,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.248363,...,39.0,9497.0,9661.0,39.0,8819.0,9666.0,9,62.8000,2024-09-30,62.8
17541,2024-10-01,South Africa,4120,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.280126,...,37.0,13205.0,14229.0,37.0,10445.0,14686.0,10,61.5000,2024-10-31,61.5
17542,2024-11-01,South Africa,5150,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.268753,...,35.0,12006.0,13720.0,35.0,11126.0,14181.0,11,61.5000,2024-11-29,61.5
17543,2024-12-01,South Africa,9350,2024,ZAF,6253.371582,4.002607e+11,4.361152,33.168,0.165591,...,43.0,14636.0,16380.0,42.0,14688.0,16647.0,12,59.7000,2024-12-31,59.7

In [263]:
with_even_more_exchange_rates[with_even_more_exchange_rates["Country/Continent"] == "New Zealand"]
with_even_more_exchange_rates["Date"] = with_even_more_exchange_rates["Date_x"]
with_even_more_exchange_rates.drop(columns=["Date_x","Date_y","Year", "Month", "TWI", "Country Code"], inplace=True)

In [265]:
with_even_more_exchange_rates.rename(columns={'value':"Exchange Rate/TWI"}, inplace=True)

In [267]:
with_even_more_exchange_rates.to_csv("../processed-csvs/combined_data.csv")